import colors from "./colors.js";

export const tags = [
	{ name: "All", color: "#333" },
	{ name: "Marketing", color: colors.success },
	{ name: "Management", color: colors.info },
	{ name: "HR & Recruiting", color: colors.warning },
	{ name: "Design", color: colors.rose },
	{ name: "Development", color: colors.violet },
];

export const courses = [
	{
		image: "img/courses/image-8.jpg",
		alt: "Google Ads",
		tag: tags[1],
		title: "The Ultimate Google Ads Training Course",
		price: 100,
		author: "Jerome Bell",
	},
	{
		image: "img/courses/image-7.jpg",
		alt: "Product Management",
		tag: tags[2],
		title: "Product Management Fundamentals",
		price: 480,
		author: "Marvin McKinney",
	},
	{
		image: "img/courses/image-6.jpg",
		alt: "HR Management and Analytics",
		tag: tags[3],
		title: "HR Management and Analytics",
		price: 200,
		author: "Leslie Alexander Li",
	},
	{
		image: "img/courses/image-5.jpg",
		alt: "Brand Management & PR Communications",
		tag: tags[1],
		title: "Brand Management & PR Communications",
		price: 530,
		author: "Kristin Watson",
	},
	{
		image: "img/courses/image-4.jpg",
		alt: "Graphic Design Basic",
		tag: tags[4],
		title: "Graphic Design Basic",
		price: 500,
		author: "Guy Hawkins",
	},
	{
		image: "img/courses/image-3.jpg",
		alt: "Business Development Management",
		tag: tags[2],
		title: "Business Development Management",
		price: 400,
		author: "Dianne Russell",
	},
	{
		image: "img/courses/image-2.jpg",
		alt: "Highload Software Architecture",
		tag: tags[5],
		title: "Highload Software Architecture",
		price: 600,
		author: "Brooklyn Simmons",
	},
	{
		image: "img/courses/image-1.jpg",
		alt: "Human Resources – Selection and Recruitment",
		tag: tags[3],
		title: "Human Resources – Selection and Recruitment",
		price: 150,
		author: "Kathryn Murphy",
	},
	{
		image: "img/courses/image.jpg",
		alt: "User Experience. Human-centered Design",
		tag: tags[4],
		title: "User Experience. Human-centered Design",
		price: 240,
		author: "Cody Fisher",
	},
];
